name: Renovate
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 11 * * *" # 3 AM PST = 11 AM UDT
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v34.149.0
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
