name: Renovate
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 11 * * *" # 3 AM PST = 11 AM UDT
  workflow_dispatch:

env:
  configurationFile: renovate.json

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - name: Dry run for PRs
        if: github.event_name == 'pull_request'
        run: |
          jq '.+= {"dryRun": "full"}' ${{ env.configurationFile }}
          cat ${{ env.configurationFile }}

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v34.149.0
        with:
          configurationFile: ${{ env.configurationFile }}
          token: ${{ secrets.RENOVATE_TOKEN }}
